// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 09/12/2025, 15:30:11
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/code/antonioyosica/antonioyosica-website/v1/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/code/antonioyosica/antonioyosica-website/v1/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/code/antonioyosica/antonioyosica-website/v1/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/code/antonioyosica/antonioyosica-website/v1/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/code/antonioyosica/antonioyosica-website/v1/src/plugins/**/*.{js,ts,mjs}","C:/code/antonioyosica/antonioyosica-website/v1/src/composables/**/*.{js,ts,mjs}","C:/code/antonioyosica/antonioyosica-website/v1/src/utils/**/*.{js,ts,mjs}","C:/code/antonioyosica/antonioyosica-website/v1/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/code/antonioyosica/antonioyosica-website/v1/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/code/antonioyosica/antonioyosica-website/v1/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/code/antonioyosica/antonioyosica-website/v1/src/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;